AWSTemplateFormatVersion: "2010-09-09"
Description: IAM role for slack bot events


Parameters:

  IamRoleName:
    Type: String
    Description: Name of the IAM role
    Default: slack-bot-events-role

  OwnerContact:
    Type: String
    Description: Name of the IAM role
    Default: netaaakash@gmail.com


  # InstanceTypeParameter:
  #   Type: String
  #   Default: t2.micro
  #   AllowedValues:
  #     - t2.micro
  #     - m1.small
  #     - m1.large
  #   Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.


Resources: 
  RootRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      RoleName:
        Fn::Sub: ${IamRoleName}
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              Service: 
                - "lambda.amazonaws.com"
            Action: 
              - "sts:AssumeRole"

      Tags:
        - Key: Owner
          Value: !Ref OwnerContact


  RolePolicies: 
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: "root"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Action: "*"
            Resource: "*"
      Roles: 
        - Ref: "RootRole"
